[package]
name = "si"
version = "0.0.1"
authors = ["Oliver Schneider <rust-si1949781094849131978611@oli-obk.de>"]
description = "really simple to use panicking input functions"
homepage = "https://github.com/oli-obk/rust-si"
repository = "https://github.com/oli-obk/rust-si"
readme = "README.md"
keywords = ["io", "read", "readline"]